### ISSUE TITLE
node.js 分类错误

### ISSUE THREAD

**Issue by xuekai-china** [LeoHsiao1/Notes#11]
从我个人角度来看：我把 node.js 归类为一门后端开发语言，不是一个前端框架，它只是采用了 js 特性和语法的设计，而其能力是在服务端，和前端大不相同。

供您参考！

**Comment by LeoHsiao1** [comment]
谢谢你的指正。
我对 nodejs 不怎么了解，所以把它跟 npm 等前端构建工具放一起了。现在我把它归类为后端框架。
